### ISSUE TITLE
Containers Bridge (upstream)

### ISSUE THREAD

**Issue by arcarruda** [codedge/aws-fargate-with-php#1]
Thank you very much for sharing this content, it's helping me a lot.

So I got an issue about the communication between nginx and php-fpm containers. I got this error: "host not found in upstream "php-fpm:9000""
The Fargate doesn't allow use hostname parameter in the task definition. How did you handled with this communication?

Thank you again,

**Comment by codedge** [comment]
Hey @arcarruda 

as the config use [`awsvpc`](https://github.com/codedge/aws-fargate-with-php/blob/master/task-definition.json#L85) you can try setting `php-fpm:9000` to `127.0.0.1:9000`. `awsvpc`makes it possible to connect to container within the same vpc just via `localhost:<port>`.

Btw, that's what I use in my [nginx config](https://github.com/codedge/aws-fargate-with-php/blob/master/docker/nginx/conf.d/default.conf#L23).

**Comment by codedge** [comment]
I hope you could solve your problem. Just create a new issue for any new questions or problem.
